name: Unit Tests

on:
  push:
    branches:
      - development

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install dependencies
      run: npm install

    - name: Run unit tests
      run: npm test

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        title: 'PR Automático: Pruebas unitarias pasadas'
        body: 'Este PR fue creado automáticamente porque las pruebas unitarias pasaron.'
        branch: development
        labels: |
            automated pr
